server:
  port: 8085

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  datasource:
    master:
      jdbc-url: jdbc:sqlserver://10.173.234.82:2708;databaseName=GD_FOTC
      username: sa
      password: hgrica1@
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        connection-test-query: select 1
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: hgitsHikariCP

    slave:
      jdbc-url: jdbc:sqlserver://10.173.234.82:2708;databaseName=HOTC_IMPORT
      username: sa
      password: hgrica1@
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        connection-test-query: select 1
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: hgitsHikariCP

  thymeleaf:
    prefix: classpath:/templates/**
    enabled: true
    cache: false
    mode: HTML
    suffix: .html

  resources:
    static-locations: ["/templates/","/static/"]


  aop:
      proxy-target-class: true

  # 配置上传文件大小

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.hgits.hotc.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.hgits.hotc.common.mapper.MyMapper
  not-empty: false
  identity: SQLSERVER
  style: normal

pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#系统变量
hotc:
  tmpDir: E:/fotc/tmpDir/

